name: my_project
repository: "https://github.com/marcossilvajnr/monorepo_example"

packages:
  - apps/**
  - core/**
  - libraries/**

categories:
  apps:
    - apps/**
  core:
    - core/**
  libraries:
    - libraries/**

scripts:
  build:android:apps:
    run: melos exec --concurrency=3 --category="apps" --fail-fast --flutter --dir-exists="lib" -- "flutter build apk"
    description: Build all apps in this project for Android.

  build:ios:prepare:
    run: melos exec --concurrency=3 --category="apps" --fail-fast --flutter --dir-exists="lib" -- "cd ios && pod install"
    description: Prepare all apps in this project for iOS.

  build:ios:apps:
    run: melos exec --concurrency=3 --category="apps" --fail-fast --flutter --dir-exists="lib" -- "flutter build ipa"
    description: Build all apps in this project for iOS.

  test:core_unit_test:
    run: melos exec --concurrency=3 --category="core" --fail-fast --flutter --dir-exists="test" -- "flutter test --no-pub --coverage"
    description: Run Flutter tests for all core packages in this project.

  test:libraries_unit_test:
    run: melos exec --concurrency=3 --category="libraries" --fail-fast --flutter --dir-exists="test" -- "flutter test --no-pub --coverage"
    description: Run Flutter tests for all libraries packages in this project.