name: Build Apps

on:
  push:
    branches:
      - main

jobs:
  build_ios_apps:
    name: Build iOS Apps
    runs-on: macos-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.6

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          melos-version: '6.1.0'
          run-bootstrap: false
      
      - name: Prepare iOS Apps
        run: melos build:ios:prepare

      - name: Build iOS Apps
        run: melos build:ios:apps

  build_android_apps:
    name: Build Android Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3  

      - name: Install Android Build Tools 30.0.3 
        run: yes | sdkmanager "build-tools;30.0.3"

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.6

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          melos_version: '6.1.0'

      - name: Build Android Apps
        run: melos build:android:apps