name: Build Android Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.19.6

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Setup Melos
        run: melos bootstrap

      - name: Build Android Apps
        run: melos exec --concurrency=5 --category="apps" --fail-fast --flutter --dir-exists="lib" -- "flutter build aab"